# Generated by Django 4.0.6 on 2022-08-01 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Type', models.CharField(max_length=15)),
                ('Account_Number', models.IntegerField()),
                ('Account_Name', models.CharField(max_length=15)),
                ('Savings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=15)),
                ('Symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=15)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Transaction_Cost', models.CharField(max_length=15)),
                ('isActive', models.BooleanField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('Currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.third_party')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Employment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Marital_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='Signature',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('user_name', models.CharField(max_length=15)),
                ('Pin', models.SmallIntegerField()),
                ('isActive', models.BooleanField()),
                ('Balance', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('Amount', models.IntegerField()),
                ('Transaction_Type', models.CharField(max_length=15)),
                ('Transaction_Code', models.CharField(max_length=15)),
                ('Charge', models.IntegerField()),
                ('Status', models.CharField(max_length=15)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
                ('Destination_Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('Origin_Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_Receipt', to='wallet.account')),
                ('Third_Party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.third_party')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Field', models.DateTimeField()),
                ('Points', models.PositiveIntegerField()),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
                ('Wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('File', models.FileField(upload_to='')),
                ('Amount', models.PositiveIntegerField()),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datetime', models.DateField()),
                ('Statement', models.CharField(max_length=15)),
                ('Receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_Type', models.CharField(max_length=15)),
                ('Loan_Term', models.CharField(max_length=15)),
                ('Payment_Due_date', models.DateField()),
                ('Guarantor', models.CharField(max_length=15)),
                ('Duration', models.DateField()),
                ('Loan_Status', models.CharField(max_length=15)),
                ('Loan_borrow_date', models.DateField()),
                ('Loan_Balance', models.IntegerField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('Wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(max_length=15)),
                ('Card_Name', models.CharField(max_length=15)),
                ('Pin_Number', models.CharField(max_length=15)),
                ('CVV', models.PositiveSmallIntegerField()),
                ('expiry_date', models.DateField()),
                ('Card_Status', models.CharField(max_length=15)),
                ('Signature', models.ImageField(default=False, upload_to='')),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='Wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
    ]
