# Generated by Django 4.0.6 on 2022-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_currency_third_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
