# Generated by Django 4.0.6 on 2022-08-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Third_Party',
        ),
    ]
