# Generated by Django 4.0.6 on 2022-08-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_third_party_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Account_Name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Account_Number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Account_Type',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Savings',
            new_name='savings',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Employment_status',
            new_name='employment_status',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ID_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Marital_status',
            new_name='marital_status',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Signature',
            new_name='signature',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Charge',
            new_name='charge',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Destination_Account',
            new_name='destination_Account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Origin_Account',
            new_name='origin_Account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_Code',
            new_name='transaction_Code',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_Type',
            new_name='transaction_Type',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Pin',
            new_name='pin',
        ),
    ]
