# Generated by Django 4.0.6 on 2022-08-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_rename_account_card_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='Symbol',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Guarantor',
            new_name='guarantor',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Loan_Balance',
            new_name='loan_balance',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Loan_borrow_date',
            new_name='loan_borrow_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Loan_Status',
            new_name='loan_status',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Loan_Term',
            new_name='loan_term',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Loan_Type',
            new_name='loan_type',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Payment_Due_date',
            new_name='payment_due_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Receipt',
            new_name='receipt',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Statement',
            new_name='statement',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='File',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='Date_Field',
            new_name='date_field',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='Points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='Transaction',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
